PharmacySite-main/PharmacySiteDjango/PharmacySiteDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.urls')),
    path('admin/', admin.site.urls),
]

PharmacySite-main/PharmacySiteDjango/backend/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.homeView, name='home'),
    path('order/', views.process_order_form, name='order_medicine'),
    path('about-us/', views.about_page_view, name='about-us'),
    path('maps/', views.maps_page_view, name='maps'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PharmacySite-main/PharmacySiteDjango/backend/models.py
from django.db import models


class Pharmacy(models.Model):
    address = models.CharField(max_length=200)
    address_url = models.CharField(max_length=2000)
    opening_hours = models.CharField(max_length=200)
    image = models.ImageField(upload_to='pharmacy_buildings', blank=True, null=True)

    def __str__(self):
        return self.address


class Medicine(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='medicine_images/', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Order(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    full_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=30)

    def __str__(self):
        return f"Order {self.id} - {self.medicine.name}"

PharmacySite-main/PharmacySiteDjango/backend/forms.py
# В вашем файле forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    medicine_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(min_value=1, max_value=10, initial=1, label='Кількість', widget=forms.NumberInput(attrs={'class': 'form-control', 'style': 'width: 55px;'}))
    price = forms.DecimalField(label='Ціна', widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly', 'style': 'width: 100px;'}))

    class Meta:
        model = Order
        fields = ['pharmacy', 'full_name', 'phone_number', 'quantity', 'price']
        labels = {
            'pharmacy': 'Замовити в аптеку на вулиці:',
            'full_name': 'Повне ім`я:',
            'phone_number': 'Номер телефону:',
        }
        widgets = {
            'pharmacy': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Виберіть аптеку'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть ім`я та прізвище'}),
            'phone_number': forms.TextInput(attrs={'type': 'tel', 'class': 'form-control', 'placeholder': 'Введіть номер телефону'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['medicine_id'].widget = forms.HiddenInput()

# 'pattern': "38[0-9]{1}-[0-9]{3}-[0-9]{4}",

PharmacySite-main/PharmacySiteDjango/backend/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Medicine, Order, Pharmacy
from django.http import JsonResponse
from .forms import OrderForm


def homeView(request):
    query = request.GET.get('q')
    medicines = Medicine.objects.all()

    if query:
        medicines = filter_medicines_by_query(medicines, query)

    form = process_order_form(request)

    return render(request, 'backend/home.html', {'medicines': medicines, 'form': form})


def filter_medicines_by_query(medicines, query):
    return medicines.filter(name__icontains=query)


def process_order_form(request):
    if request.method == 'POST':
        print('post')
        form = OrderForm(request.POST)
        if form.is_valid():
            medicine_id = request.POST.get('medicine_id')
            medicine = Medicine.objects.get(id=medicine_id)
            order = form.save(commit=False)
            order.medicine = medicine
            order.save()
        print(form.errors)
        return redirect('home')
    else:
        form = OrderForm()
    return form


def about_page_view(request):
    return render(request, 'backend/about-us.html')


def maps_page_view(request):
    pharmacies = Pharmacy.objects.all()
    return render(request, 'backend/maps.html', {'pharmacies': pharmacies})

PharmacySite-main/PharmacySiteDjango/backend/templates/backend/about-us.html
{% extends './base.html' %}
{% load static %}
{% block header %}
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}
{% block content %}

<div class="container mt-4">
  <div class="row">
    <div class="col-lg-8">
      <h1>Про нас</h1>
      <p>
        Аптека "у Алєга" працює для вашого здоров'я вже понад 20 років. Ми надаємо широкий асортимент лікарських препаратів, медичних товарів та супутніх послуг.
      </p>
      <p>
        Наша команда складається з досвідчених фармацевтів та провізорів, які допоможуть вам підібрати правильні ліки та медичні товари. Ми також пропонуємо консультації спеціалістів у галузі здоров'я, які допоможуть вам зберегти здоров'я та запобігти захворюванням.
      </p>
      <p>
        Ми прагнемо надавати нашим клієнтам якісне обслуговування та забезпечувати їх доступність до необхідних лікарських препаратів та медичних товарів.
      </p>
      <img src="/media/view.jpg" alt="Аптека" class="img-fluid rounded" style="max-width: 500px;">
    </div>
  </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/bundle/4.5.2/js/bootstrap.bundle.min.js"></script>
{% endblock %}

PharmacySite-main/PharmacySiteDjango/backend/templates/backend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% csrf_token %}
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Аптека у Алєга</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block header %}
    {% endblock %}
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Аптека у Алєга</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Головна</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about-us' %}">Про нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'maps' %}">Де ми?</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer class="footer bg-dark text-light text-center d-flex">
        <div class="container">
            <p>&copy; 2023 Аптека. Усі права захищені.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Політика конфіденційності</a></li>
                <li class="list-inline-item"><a href="#">Умови використання</a></li>
                <li class="list-inline-item"><a href="#">Карта сайту</a></li>
            </ul>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

PharmacySite-main/PharmacySiteDjango/backend/templates/backend/home.html
{% extends './base.html' %}
{% load static %}
{% block header %}
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="text-center">Ліки в наявності</h1>

        <div class="row mt-4">
            <div class="col-md-6 offset-md-3">
                <form method="GET" action="{% url 'home' %}">
                    <div class="input-group">
                        <input type="text" name="q" class='form-control' placeholder="Пошук за назвою ліків">
                        <div class="input-group-append">
                            <button class="btn btn-success" type="submit">Пошук</button>
                        </div>
                    </div>
                </form>
            </div>
            <a href="{% url 'home' %}" class="btn btn-success">Показати всі ліки</a>
        </div>

        <div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="orderModalLabel">Оформлення замовлення</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="orderForm" method="post" action="{% url 'order_medicine' %}">
                            {% csrf_token %}
                            <p>{{ form.pharmacy.label }}</p>
                            <p>{{ form.pharmacy }}</p>
                            <p>{{ form.full_name.label }}</p>
                            <p>{{ form.full_name }}</p>
                            <p>{{ form.phone_number.label }}</p>
                            <p>{{ form.phone_number }}</p>
                            <div style="display: flex; align-items: center;">
                                <div style="flex: 1;">
                                    <p>{{ form.quantity.label }}</p>
                                    <p>{{ form.quantity }}</p>
                                </div>
                                <div>
                                    <p>{{ form.price.label }}</p>
                                    <p>{{ form.price }}</p>
                                </div>
                            </div>
                            <p>{{ form.medicine_id }}</p>
                            <input type="hidden" id="original_price" name="original_price">
                            <button type="submit" class="btn btn-success">Надіслати замовлення</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="products row mt-4">
            {% for medicine in medicines %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ medicine.image.url }}" class="card-img-top" alt="{{ medicine.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ medicine.name }}</h5>
                            <p class="card-text">{{ medicine.description }}</p>
                            <p class="card-text">Ціна: {{ medicine.price }}</p>
                            <form action="{% url 'order_medicine' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="medicine_id" value="{{ medicine.id }}">
                                <input type="hidden" name="medicine_price" value="{{ medicine.price }}">
                                <button type="button" class="btn btn-success mt-2 orderBtn" data-toggle="modal" data-target="#orderModal" data-id="{{ medicine.id }}" data-price="{{ medicine.price }}">
                                    Замовити
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.orderBtn').click(function() {
                var medicineId = $(this).data('id');
                var medicinePrice = parseFloat($(this).data('price')); // Получение цены за единицу товара
                $('#orderModal input[name="medicine_id"]').val(medicineId);
                $('#orderModal #id_price').val(medicinePrice);
                $('#orderModal p#price').text('Ціна: ' + medicinePrice.toFixed(2)); // Вывод цены за единицу
                $('#orderModal #original_price').val(medicinePrice); // Сохранение изначальной цены в скрытом поле формы
            });

            $('#id_quantity').on('input', function() {
                const quantity = parseInt($(this).val()) || 0;
                const originalPrice = parseFloat($('#orderModal #original_price').val()) || 0; // Получение изначальной цены

                const totalPrice = originalPrice * quantity; // Расчет общей стоимости

                if (!isNaN(totalPrice)) {
                    $('#id_price').val(totalPrice.toFixed(2)); // Обновление поля цены
                    $('#orderModal p#price').text('Ціна: ' + totalPrice.toFixed(2)); // Обновление текста с общей стоимостью
                } else {
                    $('#id_price').val('0.00');
                    $('#orderModal p#price').text('Ціна: 0.00');
                }
            });
            
        });

        document.getElementById('id_phone_number').addEventListener('input', function (e) {
            var x = e.target.value.replace(/\D/g, '').match(/(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,2})(\d{0,3})/);
            e.target.value = !x[2] ? x[1] : '+' + x[1] + (x[2] ? ' (' + x[2] : '') + (x[3] ? ') ' + x[3] : '') + (x[4] ? '-' + x[4] : '') + (x[5] ? '-' + x[5] : '');
        });

    </script>
{% endblock %}

PharmacySite-main/PharmacySiteDjango/backend/templates/backend/maps.html
{% extends './base.html' %}
{% load static %}
{% block header %}
    <title>Карта</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <style>
        .border-right {
            border-right: 1px solid #dee2e6;
        }
        .text-grey {
            color: #6c757d;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Наші Аптеки</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Зображення</th>
                    <th scope="col">Адреса</th>
                    <th scope="col">Години роботи</th>
                </tr>
            </thead>
            <tbody>
                {% for pharmacy in pharmacies %}
                <tr>
                    <td><img src="{{ pharmacy.image.url }}" alt="{{ pharmacy.address }}" style="max-width: 100px;"></td>
                    <td><a href='{{ pharmacy.address_url }}'>{{ pharmacy.address }}</a></td>
                    <td>{{ pharmacy.opening_hours }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}